### PR TITLE
Sf3 compatibility

### PR DESCRIPTION
**Pull request by mickaelCOLLET**
The reserved indicator "@" cannot start a plain scalar; need to quote the scalar

### CODE REVIEW

**Comment by laszlokorte** [comment]
Thank you!

**Comment by nickvergessen** [comment]
@laszlokorte would be nice, if you can tag a new release with this, so people can start using the bundle with symfony 3.0? Thanks in advance

**Comment by laszlokorte** [comment]
@nickvergessen I have added a 0.4.0 tag.

**Comment by nickvergessen** [comment]
Thanks, just noticed from the README, `./app/console assets:install web` is now `./bin/console assets:install web`

app vs. bin

**Pull request merged**
