### PR TITLE
[WIP] Require min. PHP 7.1 and Symfony 3.4

### PR DESCRIPTION
**Pull request by TomasVotruba**
### Related Changes

- move code to `/src` and tests to `/tests` instead of mixing code with meta files in repository root
    - this allows to use static analysis with ease, do not exclude `Tests` or `vendor` manually for each one
    - and orientate in code, since this is PHP standard in open-source packages

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I need help with tests. There is some custom command autloading, which is not possible since Symfony 3.4, resp. Symfony 4.

Is that external doctrine bundle needed for something or just random bundle?

I'd recommend adding those command in config manually  instead.

```yaml
# tests/services.yml
services:
    _defaults:
        autoconfigure: true

    SomeCommand: ~
```

**Comment by laszlokorte** [comment]
According to git blame you added the doctrine dependency some time ago:
https://github.com/CoreSphere/ConsoleBundle/commit/ffccee73249c6bc7081f1a63fcf07b06bdceeab3

**Comment by TomasVotruba** [comment]
Oh, shit on myself :D  :face_with_head_bandage:  :palm_tree:  thanks past me!

I'll take care of this

**Comment by TomasVotruba** [comment]
Sources for Flex package upgrade:

- https://github.com/symfony/demo/pull/673
- https://symfony.com/doc/current/setup/flex.html
- https://github.com/symfony/recipes-contrib

**Comment by TomasVotruba** [comment]
I'm sorry but It took me much more time than I expected and I don't have such great experience with imlementing packages under new Flex architecture, nor know how to test it easily. I'm not able to put more to this, **but feel free to taky any part of this and use in your own PRs.**

**Comment by laszlokorte** [comment]
Thank you for your afford! I will see if I get some time to work on this but i seems that now only the `someNonExistingCommand` test is failing? Maybe somebody else can have a look as well? @core23 ?

**Comment by core23** [comment]
Sorry, not using this bundle anymore

**Pull request closed without merging**
