### PR TITLE
routing: manage loading by bundle

### PR DESCRIPTION
**Pull request by TomasVotruba**
This moves responsibility for adding routes from user to bundle.

No need to do it manually.

### CODE REVIEW

**Comment by laszlokorte** [comment]
Oh nice, is this the common way to do this nowadays? Does the user still have a possibility to override the route?

**Comment by TomasVotruba** [comment]
This is official described way to load routes from modules:

- http://symfony.com/doc/current/cookbook/routing/custom_route_loader.html
- http://symfony.com/doc/current/reference/dic_tags.html#routing-loader
- http://stackoverflow.com/questions/19640274/symfony-2-dynamically-load-routes
- https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/RestRouteLoader.php
 

In case of change, you can always modify loader service or use your own.
But there is convention of respecting bundle's name, meaning when name is `xnameBundle`, the `xname` part is reserved keyword. Same as for `FrameworkBundle`, `AsseticBundle` etc.
So I think there is no need to worry.

**Comment by TomasVotruba** [comment]
I have 2 more PRs prepared together with complete test suite. So please wait for merging.

**Comment by laszlokorte** [comment]
Thanks for the explanation. Could you please rebase your branch?

**Comment by TomasVotruba** [comment]
@laszlokorte I will rebase when I'll finish all those PR, so it's one chunk.

**Comment by TomasVotruba** [comment]
Rebased and ready to merge.

**Comment by TomasVotruba** [comment]
Merged via #45

**Pull request closed without merging**
