### PR TITLE
Update DataCollector.php

### PR DESCRIPTION
**Pull request by mickaelCOLLET**
sf 3.4 + & 4+

(1/1) FatalErrorException
Error: Class CoreSphere\ConsoleBundle\DataCollector\DataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset)

### CODE REVIEW

**Comment by web-monster** [comment]
/**
     * {@inheritdoc}
     */
    public function reset()
    {
        return parent::reset();
    }

maybe so?

**Comment by madmath03** [comment]
Is there anyone working on integrating this PR? Compatibility with Symfony 4+ would be nice.

**Comment by SebastienTainon** [comment]
@laszlokorte Would you mind merging this to allow compatibility with Symfony4?

Thanks a lot!

**Comment by laszlokorte** [comment]
Sorry for the delay.

I agree with @web-monster that the `parent::reset()` should be called as well.

Also some some travis tests are failing. I will have to take a look at that.

**Comment by miqwit** [comment]
I implemented this to get rid of the deprecation message. Works fine. Merging this PR would be welcome.

**Comment by aliziad** [comment]
Was this update ever merged ? How do we get it in the composer repository ?

**Pull request merged**
